media: public/images
content:
  - slug: experience-en
    label: Experience (English)
    type: collection
    path: content/en/experience
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: experience-zh
    label: Experience (Chinese)
    type: collection
    path: content/zh/experience
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: project-en
    label: Project (English)
    type: collection
    path: content/en/project
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: project-zh
    label: Project (Chinese)
    type: collection
    path: content/zh/project
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: writing-en
    label: Writing (English)
    type: collection
    path: content/en/writing
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: writing-zh
    label: Writing (Chinese)
    type: collection
    path: content/zh/writing
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: creation-en
    label: Creation (English)
    type: collection
    path: content/en/creation
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text

  - slug: creation-zh
    label: Creation (Chinese)
    type: collection
    path: content/zh/creation
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: coverImage
        label: Cover Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: author
        label: Author
        type: object
        fields:
          - name: name
            label: Name
            type: string
          - name: picture
            label: Picture
            type: image
      - name: body
        label: Body
        type: rich-text
